import "@babel/polyfill";
import "./partials/helpers";
import "@comp/clients";
import "@comp/team";
import sliderResponces from "@comp/sliders/responces";
import sliderAbout from "@comp/sliders/about";
import sliderInstructions from "@comp/sliders/instructions";
import "@comp/forms/";
import "@comp/menu";
import tabsSyndicator from "@comp/tabs/syndicator";
import collapseSyndicator from "@comp/collapse/syndicator";